### ISSUE TITLE
impossible to upload intents on firefox

### ISSUE THREAD

**Issue by lunika** [Opla/front#80]
## What happen

I want to upload intents and the file button does not allow me to choose a file, when I click on it, nothing happen

## How to reproduce

use firefox and go to the builder page

![screenshot-2018-4-19 opla ai](https://user-images.githubusercontent.com/767834/38978077-9a4a5924-43b6-11e8-96e8-4738fd7094de.png)

**Comment by MaximeMorille** [comment]
I'd like to fix this issue.

Firefox doesn't open the file selector, since the input is in the button element (HTML specs: https://www.w3.org/TR/html50/forms.html#the-button-element).

A solution is to create a specific component to handle file uploads. The question is: should I create this component in ZRMC, or in the Opla project ?

**Comment by mikbry** [comment]
Thqnks @MaximeMorille  The component need to be created in zoapp-ui :
https://github.com/Zoapp/ui/tree/master/src/libs/components

ZRMC is for Material Components

**Comment by mikbry** [comment]
Ok now the component need to be used in Front
